//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.29 at 03:52:01 PM EDT 
//


package gov.samhsa.ds4p.cms.consent.mongodb.xacml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.samhsa.cms.xacml.obj package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AttributeSelector_QNAME = new QName("urn:oasis:names:tc:xacml:2.0:policy:schema:os", "AttributeSelector");
    private final static QName _PolicyCombinerParameters_QNAME = new QName("urn:oasis:names:tc:xacml:2.0:policy:schema:os", "PolicyCombinerParameters");
    private final static QName _Rule_QNAME = new QName("urn:oasis:names:tc:xacml:2.0:policy:schema:os", "Rule");
    private final static QName _Obligation_QNAME = new QName("urn:oasis:names:tc:xacml:2.0:policy:schema:os", "Obligation");
    private final static QName _Function_QNAME = new QName("urn:oasis:names:tc:xacml:2.0:policy:schema:os", "Function");
    private final static QName _VariableDefinition_QNAME = new QName("urn:oasis:names:tc:xacml:2.0:policy:schema:os", "VariableDefinition");
    private final static QName _Subject_QNAME = new QName("urn:oasis:names:tc:xacml:2.0:policy:schema:os", "Subject");
    private final static QName _Resource_QNAME = new QName("urn:oasis:names:tc:xacml:2.0:policy:schema:os", "Resource");
    private final static QName _Description_QNAME = new QName("urn:oasis:names:tc:xacml:2.0:policy:schema:os", "Description");
    private final static QName _Obligations_QNAME = new QName("urn:oasis:names:tc:xacml:2.0:policy:schema:os", "Obligations");
    private final static QName _Resources_QNAME = new QName("urn:oasis:names:tc:xacml:2.0:policy:schema:os", "Resources");
    private final static QName _ResourceAttributeDesignator_QNAME = new QName("urn:oasis:names:tc:xacml:2.0:policy:schema:os", "ResourceAttributeDesignator");
    private final static QName _Policy_QNAME = new QName("urn:oasis:names:tc:xacml:2.0:policy:schema:os", "Policy");
    private final static QName _SubjectMatch_QNAME = new QName("urn:oasis:names:tc:xacml:2.0:policy:schema:os", "SubjectMatch");
    private final static QName _EnvironmentAttributeDesignator_QNAME = new QName("urn:oasis:names:tc:xacml:2.0:policy:schema:os", "EnvironmentAttributeDesignator");
    private final static QName _AttributeValue_QNAME = new QName("urn:oasis:names:tc:xacml:2.0:policy:schema:os", "AttributeValue");
    private final static QName _PolicySetCombinerParameters_QNAME = new QName("urn:oasis:names:tc:xacml:2.0:policy:schema:os", "PolicySetCombinerParameters");
    private final static QName _ActionAttributeDesignator_QNAME = new QName("urn:oasis:names:tc:xacml:2.0:policy:schema:os", "ActionAttributeDesignator");
    private final static QName _PolicyDefaults_QNAME = new QName("urn:oasis:names:tc:xacml:2.0:policy:schema:os", "PolicyDefaults");
    private final static QName _ResourceMatch_QNAME = new QName("urn:oasis:names:tc:xacml:2.0:policy:schema:os", "ResourceMatch");
    private final static QName _RuleCombinerParameters_QNAME = new QName("urn:oasis:names:tc:xacml:2.0:policy:schema:os", "RuleCombinerParameters");
    private final static QName _XPathVersion_QNAME = new QName("urn:oasis:names:tc:xacml:2.0:policy:schema:os", "XPathVersion");
    private final static QName _ActionMatch_QNAME = new QName("urn:oasis:names:tc:xacml:2.0:policy:schema:os", "ActionMatch");
    private final static QName _PolicySet_QNAME = new QName("urn:oasis:names:tc:xacml:2.0:policy:schema:os", "PolicySet");
    private final static QName _PolicySetIdReference_QNAME = new QName("urn:oasis:names:tc:xacml:2.0:policy:schema:os", "PolicySetIdReference");
    private final static QName _EnvironmentMatch_QNAME = new QName("urn:oasis:names:tc:xacml:2.0:policy:schema:os", "EnvironmentMatch");
    private final static QName _Environments_QNAME = new QName("urn:oasis:names:tc:xacml:2.0:policy:schema:os", "Environments");
    private final static QName _PolicyIdReference_QNAME = new QName("urn:oasis:names:tc:xacml:2.0:policy:schema:os", "PolicyIdReference");
    private final static QName _CombinerParameter_QNAME = new QName("urn:oasis:names:tc:xacml:2.0:policy:schema:os", "CombinerParameter");
    private final static QName _VariableReference_QNAME = new QName("urn:oasis:names:tc:xacml:2.0:policy:schema:os", "VariableReference");
    private final static QName _Environment_QNAME = new QName("urn:oasis:names:tc:xacml:2.0:policy:schema:os", "Environment");
    private final static QName _Subjects_QNAME = new QName("urn:oasis:names:tc:xacml:2.0:policy:schema:os", "Subjects");
    private final static QName _Condition_QNAME = new QName("urn:oasis:names:tc:xacml:2.0:policy:schema:os", "Condition");
    private final static QName _AttributeAssignment_QNAME = new QName("urn:oasis:names:tc:xacml:2.0:policy:schema:os", "AttributeAssignment");
    private final static QName _CombinerParameters_QNAME = new QName("urn:oasis:names:tc:xacml:2.0:policy:schema:os", "CombinerParameters");
    private final static QName _Apply_QNAME = new QName("urn:oasis:names:tc:xacml:2.0:policy:schema:os", "Apply");
    private final static QName _Expression_QNAME = new QName("urn:oasis:names:tc:xacml:2.0:policy:schema:os", "Expression");
    private final static QName _Actions_QNAME = new QName("urn:oasis:names:tc:xacml:2.0:policy:schema:os", "Actions");
    private final static QName _Action_QNAME = new QName("urn:oasis:names:tc:xacml:2.0:policy:schema:os", "Action");
    private final static QName _PolicySetDefaults_QNAME = new QName("urn:oasis:names:tc:xacml:2.0:policy:schema:os", "PolicySetDefaults");
    private final static QName _Target_QNAME = new QName("urn:oasis:names:tc:xacml:2.0:policy:schema:os", "Target");
    private final static QName _SubjectAttributeDesignator_QNAME = new QName("urn:oasis:names:tc:xacml:2.0:policy:schema:os", "SubjectAttributeDesignator");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.samhsa.cms.xacml.obj
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FunctionType }
     * 
     */
    public FunctionType createFunctionType() {
        return new FunctionType();
    }

    /**
     * Create an instance of {@link ActionMatch }
     * 
     */
    public ActionMatch createActionMatchType() {
        return new ActionMatch();
    }

    /**
     * Create an instance of {@link PolicyCombinerParameters }
     * 
     */
    public PolicyCombinerParameters createPolicyCombinerParametersType() {
        return new PolicyCombinerParameters();
    }
    

    /**
     * Create an instance of {@link ResourceMatch }
     * 
     */
    public ResourceMatch createResourceMatchType() {
        return new ResourceMatch();
    }

    /**
     * Create an instance of {@link SubjectMatch }
     * 
     */
    public SubjectMatch createSubjectMatchType() {
        return new SubjectMatch();
    }

    /**
     * Create an instance of {@link AttributeSelector }
     * 
     */
    public AttributeSelector createAttributeSelectorType() {
        return new AttributeSelector();
    }

    /**
     * Create an instance of {@link AttributeAssignment }
     * 
     */
    public AttributeAssignment createAttributeAssignmentType() {
        return new AttributeAssignment();
    }

    /**
     * Create an instance of {@link Target }
     * 
     */
    public Target createTargetType() {
        return new Target();
    }

    /**
     * Create an instance of {@link CombinerParameters }
     * 
     */
    public CombinerParameters createCombinerParametersType() {
        return new CombinerParameters();
    }

    /**
     * Create an instance of {@link SubjectAttributeDesignator }
     * 
     */
    public SubjectAttributeDesignator createSubjectAttributeDesignatorType() {
        return new SubjectAttributeDesignator();
    }

    /**
     * Create an instance of {@link VariableReference }
     * 
     */
    public VariableReference createVariableReferenceType() {
        return new VariableReference();
    }

    /**
     * Create an instance of {@link Environment }
     * 
     */
    public Environment createEnvironmentType() {
        return new Environment();
    }

    /**
     * Create an instance of {@link Obligation }
     * 
     */
    public Obligation createObligationType() {
        return new Obligation();
    }

    /**
     * Create an instance of {@link PolicySet }
     * 
     */
    public PolicySet createPolicySetType() {
        return new PolicySet();
    }

    /**
     * Create an instance of {@link Resource }
     * 
     */
    public Resource createResourceType() {
        return new Resource();
    }

    /**
     * Create an instance of {@link CombinerParameter }
     * 
     */
    public CombinerParameter createCombinerParameterType() {
        return new CombinerParameter();
    }

    /**
     * Create an instance of {@link RuleCombinerParameters }
     * 
     */
    public RuleCombinerParameters createRuleCombinerParametersType() {
        return new RuleCombinerParameters();
    }

    /**
     * Create an instance of {@link EnvironmentMatch }
     * 
     */
    public EnvironmentMatch createEnvironmentMatchType() {
        return new EnvironmentMatch();
    }
    
    /**
     * Create an instance of {@link Condition }
     * 
     */
    public Condition createConditionType() {
        return new Condition();
    }

    /**
     * Create an instance of {@link ActionsType }
     * 
     */
    /*public ActionsType createActionsType() {
        return new ActionsType();
    }*/

    /**
     * Create an instance of {@link PolicySetCombinerParameters }
     * 
     */
    public PolicySetCombinerParameters createPolicySetCombinerParametersType() {
        return new PolicySetCombinerParameters();
    }

    /**
     * Create an instance of {@link Action }
     * 
     */
    public Action createActionType() {
        return new Action();
    }

    /**
     * Create an instance of {@link Policy }
     * 
     */
    public Policy createPolicyType() {
        return new Policy();
    }

    /**
     * Create an instance of {@link IdReferenceType }
     * 
     */
    public IdReferenceType createIdReferenceType() {
        return new IdReferenceType();
    }
    

    /**
     * Create an instance of {@link DefaultsType }
     * 
     */
    public DefaultsType createDefaultsType() {
        return new DefaultsType();
    }

    /**
     * Create an instance of {@link AttributeDesignator }
     * 
     */
    public AttributeDesignator createAttributeDesignatorType() {
        return new AttributeDesignator();
    }

    /**
     * Create an instance of {@link Rule }
     * 
     */
    public Rule createRuleType() {
        return new Rule();
    }

    /**
     * Create an instance of {@link Subject }
     * 
     */
    public Subject createSubjectType() {
        return new Subject();
    }

    /**
     * Create an instance of {@link AttributeValue }
     * 
     */
    public AttributeValue createAttributeValueType() {
        return new AttributeValue();
    }

    /**
     * Create an instance of {@link ApplyType }
     * 
     */
    public ApplyType createApplyType() {
        return new ApplyType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributeSelector }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:xacml:2.0:policy:schema:os", name = "AttributeSelector", substitutionHeadNamespace = "urn:oasis:names:tc:xacml:2.0:policy:schema:os", substitutionHeadName = "Expression")
    public JAXBElement<AttributeSelector> createAttributeSelector(AttributeSelector value) {
        return new JAXBElement<AttributeSelector>(_AttributeSelector_QNAME, AttributeSelector.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PolicyCombinerParameters }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:xacml:2.0:policy:schema:os", name = "PolicyCombinerParameters")
    public JAXBElement<PolicyCombinerParameters> createPolicyCombinerParameters(PolicyCombinerParameters value) {
        return new JAXBElement<PolicyCombinerParameters>(_PolicyCombinerParameters_QNAME, PolicyCombinerParameters.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Rule }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:xacml:2.0:policy:schema:os", name = "Rule")
    public JAXBElement<Rule> createRule(Rule value) {
        return new JAXBElement<Rule>(_Rule_QNAME, Rule.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Obligation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:xacml:2.0:policy:schema:os", name = "Obligation")
    public JAXBElement<Obligation> createObligation(Obligation value) {
        return new JAXBElement<Obligation>(_Obligation_QNAME, Obligation.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FunctionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:xacml:2.0:policy:schema:os", name = "Function", substitutionHeadNamespace = "urn:oasis:names:tc:xacml:2.0:policy:schema:os", substitutionHeadName = "Expression")
    public JAXBElement<FunctionType> createFunction(FunctionType value) {
        return new JAXBElement<FunctionType>(_Function_QNAME, FunctionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Subject }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:xacml:2.0:policy:schema:os", name = "Subject")
    public JAXBElement<Subject> createSubject(Subject value) {
        return new JAXBElement<Subject>(_Subject_QNAME, Subject.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Resource }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:xacml:2.0:policy:schema:os", name = "Resource")
    public JAXBElement<Resource> createResource(Resource value) {
        return new JAXBElement<Resource>(_Resource_QNAME, Resource.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:xacml:2.0:policy:schema:os", name = "Description")
    public JAXBElement<String> createDescription(String value) {
        return new JAXBElement<String>(_Description_QNAME, String.class, null, value);
    }
        
    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributeDesignator }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:xacml:2.0:policy:schema:os", name = "ResourceAttributeDesignator", substitutionHeadNamespace = "urn:oasis:names:tc:xacml:2.0:policy:schema:os", substitutionHeadName = "Expression")
    public JAXBElement<AttributeDesignator> createResourceAttributeDesignator(AttributeDesignator value) {
        return new JAXBElement<AttributeDesignator>(_ResourceAttributeDesignator_QNAME, AttributeDesignator.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Policy }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:xacml:2.0:policy:schema:os", name = "Policy")
    public JAXBElement<Policy> createPolicy(Policy value) {
        return new JAXBElement<Policy>(_Policy_QNAME, Policy.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SubjectMatch }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:xacml:2.0:policy:schema:os", name = "SubjectMatch")
    public JAXBElement<SubjectMatch> createSubjectMatch(SubjectMatch value) {
        return new JAXBElement<SubjectMatch>(_SubjectMatch_QNAME, SubjectMatch.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributeDesignator }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:xacml:2.0:policy:schema:os", name = "EnvironmentAttributeDesignator", substitutionHeadNamespace = "urn:oasis:names:tc:xacml:2.0:policy:schema:os", substitutionHeadName = "Expression")
    public JAXBElement<AttributeDesignator> createEnvironmentAttributeDesignator(AttributeDesignator value) {
        return new JAXBElement<AttributeDesignator>(_EnvironmentAttributeDesignator_QNAME, AttributeDesignator.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributeValue }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:xacml:2.0:policy:schema:os", name = "AttributeValue", substitutionHeadNamespace = "urn:oasis:names:tc:xacml:2.0:policy:schema:os", substitutionHeadName = "Expression")
    public JAXBElement<AttributeValue> createAttributeValue(AttributeValue value) {
        return new JAXBElement<AttributeValue>(_AttributeValue_QNAME, AttributeValue.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PolicySetCombinerParameters }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:xacml:2.0:policy:schema:os", name = "PolicySetCombinerParameters")
    public JAXBElement<PolicySetCombinerParameters> createPolicySetCombinerParameters(PolicySetCombinerParameters value) {
        return new JAXBElement<PolicySetCombinerParameters>(_PolicySetCombinerParameters_QNAME, PolicySetCombinerParameters.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributeDesignator }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:xacml:2.0:policy:schema:os", name = "ActionAttributeDesignator", substitutionHeadNamespace = "urn:oasis:names:tc:xacml:2.0:policy:schema:os", substitutionHeadName = "Expression")
    public JAXBElement<AttributeDesignator> createActionAttributeDesignator(AttributeDesignator value) {
        return new JAXBElement<AttributeDesignator>(_ActionAttributeDesignator_QNAME, AttributeDesignator.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DefaultsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:xacml:2.0:policy:schema:os", name = "PolicyDefaults")
    public JAXBElement<DefaultsType> createPolicyDefaults(DefaultsType value) {
        return new JAXBElement<DefaultsType>(_PolicyDefaults_QNAME, DefaultsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResourceMatch }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:xacml:2.0:policy:schema:os", name = "ResourceMatch")
    public JAXBElement<ResourceMatch> createResourceMatch(ResourceMatch value) {
        return new JAXBElement<ResourceMatch>(_ResourceMatch_QNAME, ResourceMatch.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RuleCombinerParameters }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:xacml:2.0:policy:schema:os", name = "RuleCombinerParameters")
    public JAXBElement<RuleCombinerParameters> createRuleCombinerParameters(RuleCombinerParameters value) {
        return new JAXBElement<RuleCombinerParameters>(_RuleCombinerParameters_QNAME, RuleCombinerParameters.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:xacml:2.0:policy:schema:os", name = "XPathVersion")
    public JAXBElement<String> createXPathVersion(String value) {
        return new JAXBElement<String>(_XPathVersion_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActionMatch }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:xacml:2.0:policy:schema:os", name = "ActionMatch")
    public JAXBElement<ActionMatch> createActionMatch(ActionMatch value) {
        return new JAXBElement<ActionMatch>(_ActionMatch_QNAME, ActionMatch.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PolicySet }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:xacml:2.0:policy:schema:os", name = "PolicySet")
    public JAXBElement<PolicySet> createPolicySet(PolicySet value) {
        return new JAXBElement<PolicySet>(_PolicySet_QNAME, PolicySet.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:xacml:2.0:policy:schema:os", name = "PolicySetIdReference")
    public JAXBElement<IdReferenceType> createPolicySetIdReference(IdReferenceType value) {
        return new JAXBElement<IdReferenceType>(_PolicySetIdReference_QNAME, IdReferenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EnvironmentMatch }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:xacml:2.0:policy:schema:os", name = "EnvironmentMatch")
    public JAXBElement<EnvironmentMatch> createEnvironmentMatch(EnvironmentMatch value) {
        return new JAXBElement<EnvironmentMatch>(_EnvironmentMatch_QNAME, EnvironmentMatch.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:xacml:2.0:policy:schema:os", name = "PolicyIdReference")
    public JAXBElement<IdReferenceType> createPolicyIdReference(IdReferenceType value) {
        return new JAXBElement<IdReferenceType>(_PolicyIdReference_QNAME, IdReferenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CombinerParameter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:xacml:2.0:policy:schema:os", name = "CombinerParameter")
    public JAXBElement<CombinerParameter> createCombinerParameter(CombinerParameter value) {
        return new JAXBElement<CombinerParameter>(_CombinerParameter_QNAME, CombinerParameter.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VariableReference }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:xacml:2.0:policy:schema:os", name = "VariableReference", substitutionHeadNamespace = "urn:oasis:names:tc:xacml:2.0:policy:schema:os", substitutionHeadName = "Expression")
    public JAXBElement<VariableReference> createVariableReference(VariableReference value) {
        return new JAXBElement<VariableReference>(_VariableReference_QNAME, VariableReference.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Environment }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:xacml:2.0:policy:schema:os", name = "Environment")
    public JAXBElement<Environment> createEnvironment(Environment value) {
        return new JAXBElement<Environment>(_Environment_QNAME, Environment.class, null, value);
    }
    
    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Condition }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:xacml:2.0:policy:schema:os", name = "Condition")
    public JAXBElement<Condition> createCondition(Condition value) {
        return new JAXBElement<Condition>(_Condition_QNAME, Condition.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributeAssignment }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:xacml:2.0:policy:schema:os", name = "AttributeAssignment")
    public JAXBElement<AttributeAssignment> createAttributeAssignment(AttributeAssignment value) {
        return new JAXBElement<AttributeAssignment>(_AttributeAssignment_QNAME, AttributeAssignment.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CombinerParameters }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:xacml:2.0:policy:schema:os", name = "CombinerParameters")
    public JAXBElement<CombinerParameters> createCombinerParameters(CombinerParameters value) {
        return new JAXBElement<CombinerParameters>(_CombinerParameters_QNAME, CombinerParameters.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ApplyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:xacml:2.0:policy:schema:os", name = "Apply", substitutionHeadNamespace = "urn:oasis:names:tc:xacml:2.0:policy:schema:os", substitutionHeadName = "Expression")
    public JAXBElement<ApplyType> createApply(ApplyType value) {
        return new JAXBElement<ApplyType>(_Apply_QNAME, ApplyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExpressionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:xacml:2.0:policy:schema:os", name = "Expression")
    public JAXBElement<ExpressionType> createExpression(ExpressionType value) {
        return new JAXBElement<ExpressionType>(_Expression_QNAME, ExpressionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActionsType }{@code >}}
     * 
     */
    /*@XmlElementDecl(namespace = "urn:oasis:names:tc:xacml:2.0:policy:schema:os", name = "Actions")
    public JAXBElement<ActionsType> createActions(ActionsType value) {
        return new JAXBElement<ActionsType>(_Actions_QNAME, ActionsType.class, null, value);
    }*/

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Action }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:xacml:2.0:policy:schema:os", name = "Action")
    public JAXBElement<Action> createAction(Action value) {
        return new JAXBElement<Action>(_Action_QNAME, Action.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DefaultsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:xacml:2.0:policy:schema:os", name = "PolicySetDefaults")
    public JAXBElement<DefaultsType> createPolicySetDefaults(DefaultsType value) {
        return new JAXBElement<DefaultsType>(_PolicySetDefaults_QNAME, DefaultsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Target }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:xacml:2.0:policy:schema:os", name = "Target")
    public JAXBElement<Target> createTarget(Target value) {
        return new JAXBElement<Target>(_Target_QNAME, Target.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SubjectAttributeDesignator }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:xacml:2.0:policy:schema:os", name = "SubjectAttributeDesignator", substitutionHeadNamespace = "urn:oasis:names:tc:xacml:2.0:policy:schema:os", substitutionHeadName = "Expression")
    public JAXBElement<SubjectAttributeDesignator> createSubjectAttributeDesignator(SubjectAttributeDesignator value) {
        return new JAXBElement<SubjectAttributeDesignator>(_SubjectAttributeDesignator_QNAME, SubjectAttributeDesignator.class, null, value);
    }

}
