//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.29 at 03:52:01 PM EDT 
//
package gov.samhsa.ds4p.cms.consent.mongodb.xacml;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for Obligation complex type.
 *
 * <p>The following schema fragment specifies the expected content contained
 * within this class.
 *
 * <pre>
 * &lt;complexType name="Obligation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:oasis:names:tc:xacml:2.0:policy:schema:os}AttributeAssignment" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ObligationId" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="FulfillOn" use="required" type="{urn:oasis:names:tc:xacml:2.0:policy:schema:os}EffectType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 * The <Obligation> element will be used in the XACML response to notify
 * requestor that additional processing requirements are needed. This profile
 * focuses on the use of obligations to enforce patient privacy election. The
 * XACML response may contains one or more obligations. Processing of an
 * obligation is application specific. An <Obligation> may contain the object
 * (resource) action pairing information. If multiple vocabularies are used for
 * resource definitions the origin of the vocabulary MUST be identified. The
 * obligation should conform to following structure:
 * urn:oasis:names:tc:xspa:1.0:patient:<action>:<healthcareobject>:<constraint-identifier>
 * The following is an example response obligation segment. <xacml:Obligations
 * xmlns:xacml="urn:oasis:names:tc:xacml:2.0:policy:schema:os" >
 * <xacml:Obligation
 * ObligationId="urn:oasis:names:tc:xspa:1.0:patient:masked:vitals:dissenting-
 * subject-id" FulfillOn="Permit"> </xacml:Obligation> </xacml:Obligations>
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ObligationType", propOrder = {
    "attributeAssignment"
})
public class Obligation {

    @XmlElement(name = "AttributeAssignment")
    protected List<AttributeAssignment> attributeAssignment;
    @XmlAttribute(name = "ObligationId", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String obligationId;
    @XmlAttribute(name = "FulfillOn", required = true)
    protected String fulfillOn;

    /**
     * Gets the value of the attributeAssignment property.
     *
     * <p> This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the attributeAssignment property.
     *
     * <p> For example, to add a new item, do as follows:
     * <pre>
     *    getAttributeAssignment().add(newItem);
     * </pre>
     *
     *
     * <p> Objects of the following type(s) are allowed in the list
     * {@link AttributeAssignment }
     *
     *
     */
    public List<AttributeAssignment> getAttributeAssignment() {
        if (attributeAssignment == null) {
            attributeAssignment = new ArrayList<AttributeAssignment>();
        }
        return this.attributeAssignment;
    }

    /**
     * Gets the value of the obligationId property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getObligationId() {
        return obligationId;
    }

    /**
     * Sets the value of the obligationId property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setObligationId(String value) {
        this.obligationId = value;
    }

    /**
     * Gets the value of the fulfillOn property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getFulfillOn() {
        return fulfillOn;
    }

    /**
     * Sets the value of the fulfillOn property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setFulfillOn(String value) {
        this.fulfillOn = value;
    }
}
